FROM golang:1.23-alpine3.19 AS builder

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

RUN apk add curl

EXPOSE 12000

CMD ["air", "-c", ".air.toml"]
