FROM golang:1.23-alpine3.19 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

RUN go build -o main /app/cmd/

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 11000

ENTRYPOINT ["/app/main"]

