// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, id uuid.UUID) error
	GetTask(ctx context.Context, id uuid.UUID) (Task, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTasksByCompletion(ctx context.Context, arg ListTasksByCompletionParams) ([]Task, error)
	UpdateTaskCompletion(ctx context.Context, arg UpdateTaskCompletionParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
