// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
	title,
	description
) VALUES (
	$1, $2
)
RETURNING id, title, description, completed, updated_at, created_at
`

type CreateTaskParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Title, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, completed, updated_at, created_at FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, completed, updated_at, created_at FROM tasks
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCompletion = `-- name: ListTasksByCompletion :many
SELECT id, title, description, completed, updated_at, created_at FROM tasks
WHERE completed = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListTasksByCompletionParams struct {
	Completed bool  `json:"completed"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListTasksByCompletion(ctx context.Context, arg ListTasksByCompletionParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByCompletion, arg.Completed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskCompletion = `-- name: UpdateTaskCompletion :one
UPDATE tasks
  set completed = $2
WHERE id = $1
RETURNING id, title, description, completed, updated_at, created_at
`

type UpdateTaskCompletionParams struct {
	ID        uuid.UUID `json:"id"`
	Completed bool      `json:"completed"`
}

func (q *Queries) UpdateTaskCompletion(ctx context.Context, arg UpdateTaskCompletionParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskCompletion, arg.ID, arg.Completed)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
